# Standard Ruby configuration
# See https://github.com/standardrb/standard for more options

fix: true

parallel: true

format: progress

plugins:
  - standard-performance

ignore:
  - bin/**/*
  - db/*
  - vendor/**/*
  - tmp/**/*
  - log/**/*
  - storage/**/*
  - coverage/**/*
  - uploads/**/*

rubocop:
  Style/AccessModifierDeclarations:
    EnforcedStyle: inline
  Lint/UselessAssignment:
    Enabled: false
  Style/FrozenStringLiteralComment:
    Enabled: false
